### PR TITLE
fix reset wallet

### LINKED ISSUE #157: New wallet created but same tark address
**Repo Steps**:
Have an existing wallet
take note of the tark address
Run
```
docker rm fulmine --force 
docker volume rm fulmine-data --force
docker run -d \
  --name fulmine \
  -p 7000:7000 \
  -p 7001:7001 \
  -e FULMINE_ARK_SERVER="https://mutinynet.arkade.sh" \
  -v fulmine-data:/app/data \
  ghcr.io/arklabshq/fulmine:latest
```

Create a new wallet
observe the receiving tark address
check the nsec in Backup wallet

**Expected Result?**:
A new address should be derived as the nsec is different from the previous one

**Actual Results**:
same address of the previous wallet

**Reproducibility**:
_No details provided._

**Logs**:
_No details provided._

**Build Info**:
commit 7bf3062

**Video capture (link)**:

https://github.com/user-attachments/assets/dab8e2e8-f1a3-4c96-a643-49bace7256fc

and

https://github.com/user-attachments/assets/4d956327-e26f-4b28-9946-d0402fc4612e

### PR DESCRIPTION
**Pull request by bordalix**
Closes #157 

Preview:

https://github.com/user-attachments/assets/07ca1667-e17b-40a1-a7a8-85bc28d41f73

@tiero please review

### CODE REVIEW

File: internal/core/application/service.go [hunk 1]
```diff
@@ -290,20 +290,10 @@ func (s *Service) UnlockNode(ctx context.Context, password string) error {
...
-	if err := s.settingsRepo.CleanSettings(ctx); err != nil {
-		return err
-	}
-	if err := s.storeRepo.ConfigStore().CleanData(ctx); err != nil {
-		// nolint:all
-		s.settingsRepo.AddSettings(ctx, *backup)
-		return err
-	}
-
+func (s *Service) ResetWallet(ctx context.Context) error {
```
Comment (altafan) [inline internal/core/application/service.go:293]: this can be void now (remove the return at the end of the func body):
```suggestion
func (s *Service) ResetWallet(ctx context.Context) {
```

**Review by altafan — APPROVED** [review]
